[package]
name = "screenext"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
idevice = { version = "0.1.49", features = ["core_device_proxy", "usbmuxd"] }
tokio = { version = "1", features = ["full"] }
etherparse = "0.19"
env_logger = "0.11"
log = "0.4"
gstreamer = "0.24.3"
gstreamer-app = "0.24.2"
ashpd = "0.12.0"

[patch.crates-io]
idevice = { git = "https://github.com/Dreaming-Codes/idevice", branch = "vectorized-io" }
